name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.PARENT_REPO }}
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
          submodules: recursive

      - name: submodules recursively
        run: git submodule update --init --recursive
